### ISSUE TITLE
Uncaught TypeError: Cannot read property 'left' of undefined

### ISSUE THREAD

**Issue by ghost** [AshesOfOwls/jquery.shapeshift#33]
The console gives me the error, "Uncaught TypeError: Cannot read property 'left' of undefined", whenever I try to drag the last child. For example, when I try to drag "Child Element 3" in:

``` html
<div class="container">
    <div>Child Element 1</div>
    <div>Child Element 2</div>
    <div>Child Element 3</div>
</div>
```

However, I do not get this error when I only have 2 child elements.

This is the CSS:

``` css
.container {
    position: relative;
    width: 100%;
    border: 1px solid #aaa;
}

.container div {
    position: absolute;
    height: 100px;
    width: 100px;
    border: 1px solid #aaa;
    cursor: move;
}
```

This is the JS:

``` javascript
jQuery(function ($) {
    $('.container').shapeshift();
});
```
